[Profile]
ID=WS
Version=9
[Telnet3270]
HostName=172.105.135.161
HostPortNumber=22
Security=N
SecurityPackage=MS
SNIServerName=
CertSelection=AUTOSELECT
[Communication]
Link=telnet3270
AutoConnect=N
[3270]
QueryReplyMode=Auto
HostCodePage=037-U
[Keyboard]
CuaKeyboard=1
Language=United-States
IBMDefaultKeyboard=N
DefaultKeyboard=C:\Users\2457918\AppData\Roaming\IBM\Personal Communications\TN3270.KMP
[LastExitView]
A=3 -7 0 656 764 7 8 25 400 0 PComm Session— 37
[Transfer]
DefaultDirectory=C:\Users\2457918\OneDrive - Cognizant\Documents
PacketSize=8000
PCCodePage=1252
[Window]
ViewFlags=CF00
RuleLinePos=28 5
SessFlags=3886A
